<?php
$siteTitle = 'Admin controls';
?>
<section class="panel">
    <div class="topbar"><div><p class="eyebrow">Governance</p><h2>Admin controls</h2><p class="muted">Restricted operational controls with an immutable audit trail.</p></div><a href="/admin/strategies" class="secondary-button">Strategy API</a></div>
    <div class="stats-grid"><article class="stat-card primary"><span>Customers</span><strong><?= (int) ($customerCount ?? 0); ?></strong></article><article class="stat-card"><span>Administrators</span><strong><?= (int) ($adminCount ?? 0); ?></strong></article><article class="stat-card"><span>Audit events</span><strong><?= count($auditEvents ?? []); ?></strong></article></div>
    <h3>User access</h3><div class="table-wrap"><table><thead><tr><th>User</th><th>Email</th><th>State</th><th>Action</th></tr></thead><tbody><?php foreach (($users ?? []) as $item): ?><tr><td><?= htmlspecialchars($item['full_name'], ENT_QUOTES, 'UTF-8'); ?></td><td><?= htmlspecialchars($item['email'], ENT_QUOTES, 'UTF-8'); ?></td><td><?= (int) $item['is_active'] ? 'Active' : 'Suspended'; ?></td><td><?php if ((int) $item['id'] !== (int) ($_SESSION['user']['id'] ?? 0)): ?><form method="post" action="/admin/set-user-status"><input type="hidden" name="_token" value="<?= htmlspecialchars(csrf_token(), ENT_QUOTES, 'UTF-8'); ?>"><input type="hidden" name="user_id" value="<?= (int) $item['id']; ?>"><input type="hidden" name="active" value="<?= (int) !$item['is_active']; ?>"><button type="submit"><?= (int) $item['is_active'] ? 'Suspend' : 'Activate'; ?></button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
    <h3>Recent audit events</h3><ul class="transaction-list"><?php foreach (($auditEvents ?? []) as $event): ?><li><div><strong><?= htmlspecialchars($event['action'], ENT_QUOTES, 'UTF-8'); ?></strong><small><?= htmlspecialchars($event['email'] ?? 'system', ENT_QUOTES, 'UTF-8'); ?> · <?= htmlspecialchars($event['created_at'], ENT_QUOTES, 'UTF-8'); ?></small></div><span><?= htmlspecialchars($event['resource'], ENT_QUOTES, 'UTF-8'); ?></span></li><?php endforeach; ?></ul>
</section>
